// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'beginners-guide', // 原“入门教程”
      items: [
        { type: 'autogenerated', dirName: 'beginners-guide' },
      ],
    },
    {
      type: 'category',
      label: 'hands-on-practice', // 原“实践应用”
      items: [
        { type: 'autogenerated', dirName: 'hands-on-practice' },
      ],
    },
    {
      type: 'category',
      label: 'review-notes', // 原“复习总结”
      items: [
        { type: 'autogenerated', dirName: 'review-notes' },
      ],
    },
    {
      type: 'category',
      label: 'miscellaneous', // 原“杂项笔记”
      items: [
        { type: 'autogenerated', dirName: 'miscellaneous' },
      ],
    },
    {
      type: 'category',
      label: 'project-docs', // 原“项目文档”
      items: [
        { type: 'autogenerated', dirName: 'project-docs' },
      ],
    },
  ],
};

export default sidebars;
