// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // 仅保留你的5个分类，删除官方教程相关配置
    {
      type: 'category',
      label: '入门教程',
      items: [
        { type: 'autogenerated', dirName: 'beginners-guide' },
      ],
    },
    {
      type: 'category',
      label: '实践应用',
      items: [
        { type: 'autogenerated', dirName: 'hands-on-practice' },
      ],
    },
    {
      type: 'category',
      label: '复习总结',
      items: [
        { type: 'autogenerated', dirName: 'review-notes' },
      ],
    },
    {
      type: 'category',
      label: '杂项笔记',
      items: [
        { type: 'autogenerated', dirName: 'miscellaneous' },
      ],
    },
    {
      type: 'category',
      label: '项目文档',
      items: [
        { type: 'autogenerated', dirName: 'project-docs' },
      ],
    },
  ],
};

export default sidebars;
