// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics', // docs/tutorial-basics
        },
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras', // docs/tutorial-extras
        },
      ],
    },
    {
      type: 'category',
      label: 'Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'notes', // docs/notes
        },
      ],
    },
  ],
};

export default sidebars;